dist: trusty

sudo: required

services:
  - docker

git:
  depth: 3

before_install:
  - docker --version
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

script:
  - docker build --tag alcohol/www:latest .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin;
      docker push alcohol/www:latest;
      docker logout;
    fi
